2023-11-22 16:01:11,301 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 16:02:47,712 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 16:02:48,185 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 16:02:48,219 [INFO] form.views Рендер страницы Form
2023-11-22 16:04:01,497 [INFO] form.views Рендер страницы index
2023-11-22 16:04:35,616 [INFO] form.views Рендер страницы index
2023-11-22 16:05:57,986 [INFO] form.views Рендер страницы index
2023-11-22 16:06:16,100 [INFO] form.views Рендер страницы index_detail
2023-11-22 16:07:24,754 [INFO] form.views Рендер страницы index
2023-11-22 16:07:26,892 [INFO] form.views Рендер страницы index_detail
2023-11-22 16:07:28,034 [INFO] form.views Рендер страницы index
2023-11-22 18:39:16,736 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 18:39:17,519 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 18:39:17,563 [INFO] form.views Рендер страницы Form
2023-11-22 18:39:57,967 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 18:39:58,426 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 18:39:58,459 [INFO] form.views Рендер страницы Form
2023-11-22 18:40:57,567 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 18:40:58,182 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 18:41:47,869 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 18:41:48,356 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 18:44:37,187 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 18:44:37,840 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 18:46:01,001 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 18:46:01,695 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 18:49:11,008 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 18:49:11,610 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 18:49:11,652 [INFO] form.views Рендер страницы Form
2023-11-22 19:16:24,118 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 19:16:24,618 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 19:16:24,651 [INFO] form.views Рендер страницы Form
2023-11-22 19:24:21,495 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/urls.py changed, reloading.
2023-11-22 19:24:21,944 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 19:24:21,976 [INFO] form.views Рендер страницы Form
2023-11-22 19:26:01,023 [INFO] form.views Рендер страницы index
2023-11-22 19:26:16,637 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 42, in search_view
    search_query = FormField.objects.create(query=query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: FormField() got unexpected keyword arguments: 'query'
2023-11-22 19:28:55,514 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 42, in search_view
    search_query = FormField.objects.create(query=query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: FormField() got unexpected keyword arguments: 'query'
2023-11-22 19:46:51,988 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 19:46:52,703 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 19:46:52,781 [INFO] form.views Рендер страницы Form
2023-11-22 19:48:10,450 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 42, in search_view
    search_query = FormField.objects.create(query=query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: FormField() got unexpected keyword arguments: 'query'
2023-11-22 19:48:26,649 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 42, in search_view
    search_query = FormField.objects.create(query=query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: FormField() got unexpected keyword arguments: 'query'
2023-11-22 19:54:46,183 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 19:54:46,938 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 19:54:46,980 [INFO] form.views Рендер страницы Form
2023-11-22 19:56:18,536 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 19:56:19,140 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 19:56:19,201 [INFO] form.views Рендер страницы Form
2023-11-22 20:05:39,016 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:05:39,642 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:05:39,702 [INFO] form.views Рендер страницы Form
2023-11-22 20:05:50,199 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:05:55,876 [WARNING] django.request Not Found: /form/
2023-11-22 20:06:03,588 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:06:04,958 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:06:05,730 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:06:10,678 [INFO] form.views Рендер страницы index
2023-11-22 20:06:20,720 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view form.views.search_view didn't return an HttpResponse object. It returned None instead.
2023-11-22 20:13:37,381 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:13:37,413 [INFO] form.views Рендер страницы Form
2023-11-22 20:13:50,785 [INFO] form.views Рендер страницы index
2023-11-22 20:13:53,841 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view form.views.search_view didn't return an HttpResponse object. It returned None instead.
2023-11-22 20:14:36,969 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:14:37,619 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:14:37,659 [INFO] form.views Рендер страницы Form
2023-11-22 20:15:05,808 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:15:06,178 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:15:06,209 [INFO] form.views Рендер страницы Form
2023-11-22 20:15:37,716 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:17:37,516 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:17:37,912 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:17:37,947 [INFO] form.views Рендер страницы Form
2023-11-22 20:17:43,774 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: search_view() missing 1 required positional argument: 'name'
2023-11-22 20:18:12,735 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: search_view() missing 1 required positional argument: 'name'
2023-11-22 20:18:23,577 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: search_view() missing 1 required positional argument: 'name'
2023-11-22 20:18:30,733 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: search_view() missing 1 required positional argument: 'name'
2023-11-22 20:18:53,455 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:18:53,916 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:18:53,949 [INFO] form.views Рендер страницы Form
2023-11-22 20:19:01,377 [INFO] form.views Рендер страницы index
2023-11-22 20:19:09,476 [INFO] form.views Рендер страницы index
2023-11-22 20:19:33,294 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:20:13,359 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:21:34,455 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:21:34,882 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:21:34,917 [INFO] form.views Рендер страницы Form
2023-11-22 20:21:56,027 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:30:31,504 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:30:32,052 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:30:32,086 [INFO] form.views Рендер страницы Form
2023-11-22 20:30:54,649 [INFO] form.views Рендер страницы index
2023-11-22 20:30:56,795 [INFO] form.views Рендер страницы index
2023-11-22 20:31:04,810 [INFO] form.views Рендер страницы index
2023-11-22 20:33:01,408 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 45, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:35:31,125 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:35:32,056 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:35:32,106 [INFO] form.views Рендер страницы Form
2023-11-22 20:39:03,145 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:39:53,091 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 43, in search_view
    results = FormField.objects.filter(query=search_query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:41:20,159 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:41:20,570 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:41:20,604 [INFO] form.views Рендер страницы Form
2023-11-22 20:41:35,123 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 42, in search_view
    search_query = FormField.objects.filter(query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1423, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
2023-11-22 20:43:39,440 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:43:39,981 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:43:40,059 [INFO] form.views Рендер страницы Form
2023-11-22 20:45:27,285 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:45:27,933 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:45:27,975 [INFO] form.views Рендер страницы Form
2023-11-22 20:47:27,365 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:47:27,810 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:49:10,175 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    search_query = FormField.objects.filter(query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1423, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
2023-11-22 20:52:31,403 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:52:31,885 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:52:45,079 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    search_query = FormField.objects.filter(query=query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:52:48,264 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    search_query = FormField.objects.filter(query=query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 20:54:47,365 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:54:47,813 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:55:17,894 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: search_view() missing 1 required positional argument: 'name'
2023-11-22 20:57:22,697 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:57:23,143 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:57:57,187 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:59:24,072 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 20:59:24,469 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 20:59:39,219 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    search_query = FormField.objects.filter(query=query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 21:04:39,195 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:04:39,733 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:04:59,443 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.filter(query=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 21:05:41,886 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.filter(query=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'query' into field. Choices are: id, name, name_field, type_field
2023-11-22 21:13:07,637 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:13:08,481 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:18:45,386 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 41, in search_view
    return render(request, 'form/search_results.html', {'results': results})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 193, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'FormField' object is not iterable
2023-11-22 21:19:19,107 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'empty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 41, in search_view
    return render(request, 'form/search_results.html', {'results': results})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'empty', expected 'endblock'. Did you forget to register or load this tag?
2023-11-22 21:19:51,493 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'empty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 41, in search_view
    return render(request, 'form/search_results.html', {'results': results})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'empty', expected 'endblock'. Did you forget to register or load this tag?
2023-11-22 21:20:18,244 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'empty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 41, in search_view
    return render(request, 'form/search_results.html', {'results': results})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'empty', expected 'endblock'. Did you forget to register or load this tag?
2023-11-22 21:25:17,583 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:30:16,025 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:30:31,384 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:32:08,384 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:34:05,993 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:34:32,576 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:35:40,482 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:37:38,421 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:37:39,070 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:37:44,873 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 39, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:38:02,996 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 39, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:39:49,484 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:39:50,114 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:40:01,706 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 39, in search_view
    results = FormField.objects.get(name__icontains=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:40:57,988 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:40:58,494 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:41:05,080 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 39, in search_view
    results = FormField.objects.get(name__icontains=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 640, in get
    raise self.model.MultipleObjectsReturned(
form.models.FormField.MultipleObjectsReturned: get() returned more than one FormField -- it returned 4!
2023-11-22 21:42:03,366 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:42:04,059 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:44:03,297 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:44:03,805 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:44:22,614 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:44:23,019 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:45:47,607 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:45:48,033 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:46:52,646 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:46:53,228 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 21:47:24,533 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 39, in search_view
    results = FormField.objects.get(name__iexact=query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
form.models.FormField.DoesNotExist: FormField matching query does not exist.
2023-11-22 21:48:55,025 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 21:48:56,055 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 22:25:52,682 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    return render(request, 'form/search_results.html', {'results': results})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'else', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
2023-11-22 22:26:20,921 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py", line 40, in search_view
    return render(request, 'form/search_results.html', {'results': results})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'else', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
2023-11-22 22:37:42,272 [WARNING] django.request Not Found: /favicon.ico
2023-11-22 22:37:49,130 [WARNING] django.request Not Found: /cart/
2023-11-22 22:37:49,219 [WARNING] django.request Not Found: /apple-touch-icon-precomposed.png
2023-11-22 22:37:49,231 [WARNING] django.request Not Found: /apple-touch-icon.png
2023-11-22 22:37:49,237 [WARNING] django.request Not Found: /favicon.ico
2023-11-22 22:37:49,242 [WARNING] django.request Not Found: /apple-touch-icon-precomposed.png
2023-11-22 22:37:49,248 [WARNING] django.request Not Found: /apple-touch-icon.png
2023-11-22 22:37:49,253 [WARNING] django.request Not Found: /favicon.ico
2023-11-22 22:37:49,260 [WARNING] django.request Not Found: /cart/
2023-11-22 22:37:49,267 [WARNING] django.request Not Found: /apple-touch-icon-precomposed.png
2023-11-22 22:37:49,271 [WARNING] django.request Not Found: /apple-touch-icon.png
2023-11-22 22:37:49,276 [WARNING] django.request Not Found: /favicon.ico
2023-11-22 22:37:49,281 [WARNING] django.request Not Found: /apple-touch-icon-precomposed.png
2023-11-22 22:37:49,286 [WARNING] django.request Not Found: /apple-touch-icon.png
2023-11-22 22:37:49,291 [WARNING] django.request Not Found: /favicon.ico
2023-11-22 22:55:05,834 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 22:55:06,710 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 22:58:04,935 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 22:58:05,756 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 22:58:12,687 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view form.views.search_view didn't return an HttpResponse object. It returned None instead.
2023-11-22 22:58:15,899 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view form.views.search_view didn't return an HttpResponse object. It returned None instead.
2023-11-22 22:58:17,568 [WARNING] django.request Not Found: /form/
2023-11-22 22:58:20,820 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view form.views.search_view didn't return an HttpResponse object. It returned None instead.
2023-11-22 22:58:38,603 [ERROR] django.request Internal Server Error: /form/search/
Traceback (most recent call last):
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/kovalevigor/PycharmProjects/Form/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view form.views.search_view didn't return an HttpResponse object. It returned None instead.
2023-11-22 22:59:24,294 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 22:59:24,970 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 23:08:36,867 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 23:08:37,583 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 23:08:37,628 [INFO] form.views Рендер страницы Form
2023-11-22 23:09:40,674 [INFO] form.views Рендер страницы index
2023-11-22 23:11:36,380 [INFO] form.views Рендер страницы index
2023-11-22 23:12:12,244 [INFO] form.views Рендер страницы detail
2023-11-22 23:12:33,052 [INFO] form.views Рендер страницы index
2023-11-22 23:16:54,397 [INFO] form.views Рендер страницы index
2023-11-22 23:18:49,987 [INFO] form.views Рендер страницы index
2023-11-22 23:19:26,497 [INFO] form.views Рендер страницы index
2023-11-22 23:19:28,426 [INFO] form.views Рендер страницы detail
2023-11-22 23:19:33,044 [INFO] form.views Рендер страницы index
2023-11-22 23:19:41,738 [INFO] form.views Рендер страницы index
2023-11-22 23:20:07,965 [INFO] form.views Рендер страницы detail
2023-11-22 23:23:52,999 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/form/views.py changed, reloading.
2023-11-22 23:23:53,713 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-22 23:23:53,769 [INFO] form.views Рендер страницы Form
2023-11-22 23:23:55,522 [INFO] form.views Рендер страницы index
2023-11-22 23:24:01,224 [INFO] form.views Рендер страницы index
2023-11-22 23:24:51,124 [INFO] form.views Рендер страницы index
2023-11-23 03:35:25,751 [WARNING] django.request Bad Request: /get_form/
2023-11-23 03:36:18,469 [WARNING] django.request Not Found: /get_form/name1=value1&name2=value2/
2023-11-23 03:36:56,876 [WARNING] django.request Not Found: /get_form/name1=value1&name2=value2/
2023-11-23 03:36:57,961 [WARNING] django.request Not Found: /get_form/name1=value1&name2=value2/
2023-11-23 18:22:16,361 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-23 18:22:16,395 [INFO] form.views Рендер страницы Form
2023-11-23 19:08:16,978 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-23 19:08:17,013 [INFO] form.views Рендер страницы Form
2023-11-23 19:08:31,816 [INFO] form.views Рендер страницы index
2023-11-23 19:09:10,133 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/Myform/settings.py changed, reloading.
2023-11-23 19:09:10,808 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-23 19:09:10,870 [INFO] form.views Рендер страницы Form
2023-11-23 19:09:33,825 [INFO] form.views Рендер страницы index
2023-11-23 19:09:37,733 [INFO] form.views Рендер страницы index
2023-11-23 19:09:39,835 [INFO] form.views Рендер страницы detail
2023-11-23 19:09:41,002 [INFO] form.views Рендер страницы index
2023-11-23 19:11:27,527 [INFO] form.views Рендер страницы index
2023-11-23 19:50:34,730 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/Myform/settings.py changed, reloading.
2023-11-23 19:50:36,125 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-23 19:50:36,182 [INFO] form.views Рендер страницы Form
2023-11-23 19:51:38,224 [INFO] django.utils.autoreload /Users/kovalevigor/PycharmProjects/Form/Myform/Myform/settings.py changed, reloading.
2023-11-23 19:51:38,897 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-23 19:51:38,933 [INFO] form.views Рендер страницы Form
2023-11-23 19:58:17,870 [INFO] form.views Рендер страницы index
2023-11-23 22:55:50,614 [INFO] django.utils.autoreload Watching for file changes with StatReloader
2023-11-23 22:55:50,650 [INFO] form.views Рендер страницы Form
